apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: startpage
configMapGenerator:
  - name: index-html-configmap
    files:
      - index.html
resources:
  - deployment.yaml
  # - ingress.yaml
  - namespace.yaml
  - service.yaml
